name:                devcon5
version:             0.1.0.0
github:              "airalab/devcon5"
license:             BSD3
author:              "Alexander Krupenkin"
maintainer:          "research@aira.life"
copyright:           "(c) Airalab"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/airalab/devcon5#readme>

dependencies:
- base >= 4.7 && < 5
- robonomics-tools >= 0.5.2
- optparse-applicative
- pipes-concurrency
- monad-logger
- data-default
- base58string
- exceptions
- bytestring
- cryptonite
- microlens
- process
- aeson
- pipes
- web3
- text
- mtl

executables:
  worker:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
